### ISSUE TITLE
 Multiple Fields query does not work.

### ISSUE THREAD

**Issue by krisblau** [davideast/Querybase#12]
I have the following QueryBase setup in an HTML document using javascript:

```
var dbref = firebase.database().ref().child('notifications');
var querybaseRef = querybase.ref(dbref, ['category', 'severity', 'tenant_id', 'site_id', 'timestamp',  'source', 'event_code', 'mppa_id']);
```

Then I run the following query:

```
var queriedDbRef = querybaseRef.where({
        event_code:'999',
        category:'WebApi'
});
queriedDbRef.on('value', snap => console.log('Received:', snap.val()));

```
After running the console logs: `Received: null`. If I remove one of the specified fields and relaunch, the query succeeds and returns the correct objects.

**Comment by davideast** [comment]
@krisblau Can you create a JSBin so I can debug it?

**Comment by krisblau** [comment]
Here you go!

http://jsbin.com/wuripujozi/1/edit?html,console

**Comment by davideast** [comment]
@krisblau Yep this definitely looks like a bug. I think it has to do with indexing a large set of items. I had tested this previously but I have made some changes to the library since doing so.

Just as a perf tip, you should only index what is needed. Each index adds an extra set of data for each record, which has to be downloaded.

I need investigate a bit further so I'll get back to you in a day or so.

**Comment by krisblau** [comment]
OK thanks David!

**Comment by davideast** [comment]
@krisblau 


**Update**: I think figured it out. 

Try running the following:

```js
var queriedDbRef = querybaseRef.where({
  category:'WebApi',
  severity:'Warning',
});
```

**Comment by krisblau** [comment]
I have already left the office.. Will do first thing in the morning!

**Comment by krisblau** [comment]
It works when using the defined order.. In the future will you be optimizing the function so that the order does not matter?

**Comment by davideast** [comment]
@krisblau Yep! I have branch with the fix in already. Doing a bit more testing and I'll have it in soon 💯

**Comment by davideast** [comment]
@krisblau Can you try using this test version and let me know if it works?

https://cdn.rawgit.com/davideast/770cc035ebe9834b1de83261ddbae7ef/raw/dc50946d2ea756fc31269149f2676a4283d1e838/querybase.js

**Comment by krisblau** [comment]
I have actually run into another issue when adding a third field in the where clause.

**Comment by davideast** [comment]
@krisblau I have ran into the same thing actually. Let me do some more investigating. Thanks for checking this out!

**Comment by krisblau** [comment]
Also I did not notice you put a test version.... Trying now

**Comment by davideast** [comment]
@krisblau Yeahhh I noticed the same thing 😞 . I need to do more investigating. Give me another day or so to find the fix, I have a few ideas. Thank you for your patience!

**Comment by krisblau** [comment]
Oh ok... Thank you for all your help!

**Comment by FbertM** [comment]
Hi David, 
I watch your library (querybase) for multiple query in firebase. But I realize that your library just make multiple query for equal to . 

`var queriedDbRef = querybaseRef.where({
  category:'WebApi',
  severity:'Warning',
});`

How can I make multiple query . The first query using parameter equal to and the second for greater than. 
`var queriedDbRef = querybaseRef.where({
  category:'WebApi',
  qty>1,
});`
Can I do something like this ? 

Thank you 

Best Regard
Filbert Sugianto manunggal

**Comment by cmarrero01** [comment]
Hi @davideast , first of all, sorry for comment on an old issue, but is about this. In the readme you say this:

> Querybase takes a Firebase Database reference with a list of fields to create composite keys. You can only use up to three fields. Any more would create a crazy amount of composite keys in the database.

You can provide me a more specific detail about this?. 

I'm building a huge project with firebase, and the primary thing is a fast and performance search function, and the big problem of firebase is we can use only one orderByChild function on each query, so. Query Base sounds perfect. But, only three fields? why?, I had at least 5 fields that I like to search for.

Thanks in advance.
