### ISSUE TITLE
Please add callbacks to Push/Set. -- Code available

### ISSUE THREAD

**Issue by ghost** [davideast/Querybase#16]
Push/Set take callbacks instead of promises, would be nice to have callbacks built into the library, considering all of the additional logic.

**Comment by CTucker1327** [comment]
I tried creating a pull request for you, but it wasn't accepted. 


` /**
   * Save data to the realtime database with composite keys
   * @param {any} data
   * @return {void}
   */
  set(data, callback) {
    const dataWithIndex = this.indexify(data);
    this.ref().set(dataWithIndex, callback);
  }

  /**
   * Update data to the realtime database with composite keys
   * @param {any} data
   * @return {void}
   */
  update(data, callback) {
    const dataWithIndex = this.indexify(data);
    this.ref().update(dataWithIndex, callback);
  }

  /**
   * Push a child node to the realtime database with composite keys, if 
   * there is more than one property in the object
   * @param {any} data
   * @return {FirebaseRef}
   */
  push(data, callback) {

    // TODO: Should we return a Querybase with the option 
    // to specify child indexes?
    if (!data) { return this.ref().push(undefined, callback) }

    // If there is only one key there's no need to indexify
    if (_.keys(data).length === 1) {
      return this.ref().push(data, callback);
    }

    // Create indexes with indexed data values
    const dataWithIndex = this.indexify(data);
    // merge basic data with indexes with data
    const indexesAndData = _.merge(dataWithIndex, data);

    let firebaseRef = this.ref().push();
    firebaseRef.set(indexesAndData, callback);
    return firebaseRef;
  }`

**Comment by davideast** [comment]
Great idea!

**Comment by Domiii** [comment]
Any updates?
