### ISSUE TITLE
Multiple Query (not just equal to )

### ISSUE THREAD

**Issue by FbertM** [davideast/Querybase#18]
Hi David,
I watch your library (querybase) for multiple query in firebase. But I realize that your library just make multiple query for equal to .

var queriedDbRef = querybaseRef.where({ category:'WebApi', severity:'Warning', });

How can I make multiple query . The first query using parameter equal to and the second for greater than.
var queriedDbRef = querybaseRef.where({ category:'WebApi', qty>1 });
Can I do something like this ?

Thank you

Best Regard
Filbert Sugianto manunggal

**Comment by davideast** [comment]
@FbertM Unfortunately that won't be possible with this library. All Querybase does is combine keys in a certain order and query based upon the combination. This means we won't be able to add this type of functionality on the server. This is still possible on the client however.
