### ISSUE TITLE
Not able to import querybase

### ISSUE THREAD

**Issue by mohpra** [davideast/Querybase#19]
I am doing the following 

import {querybase} from 'querybase';

private _todosRef: any;
    private querybaseRef: any;

constructor(public af: AngularFire, public auth: FirebaseAuth, public nav: NavController, public querybase: querybase) {
    this._todosRef = firebase.database().ref('todolist/');
    this.querybaseRef = querybase.ref(this._todosRef, ['name', 'age', 'location']);}

I am getting the error Cannot find module 'querybase'

**Comment by davideast** [comment]
Only window and require calls are supported right now, but I'll be switching to ES6 modules and Webpack bundling soon.

**Comment by davideast** [comment]
@mohpra Updated to use a UMD bundle, should work fine now :)
