### ISSUE TITLE
Querybase for Android

### ISSUE THREAD

**Issue by tsadoklf** [davideast/Querybase#20]
Hi David,

Do you, by chance, have plans to create an Android version of Querybase? 

Regards,
Tsadok

**Comment by LOG-TAG** [comment]
![wantthis](https://cloud.githubusercontent.com/assets/1190344/19888308/d748679c-a053-11e6-947d-938d77ee19a9.gif)

**Comment by davideast** [comment]
@tsadoklf @LOG-TAG Unfortunately not at the time. But I do think it's a great idea :)
