### ISSUE TITLE
Fields Array

### ISSUE THREAD

**Issue by EliuFlorez** [davideast/Querybase#24]
Query Fields Array
how could perform this query

```js
const refQuery = refQuerybase.where({
    user_list: {'u9bxggdTQUgZvNJXmdMsQAeGD2z2':true}
});
```

AND

```js
"events" : {
    "-KRV9i7lFUjh-Vd0uQna" : {
      "description" : "Description - test",
      "like_count" : 1,
      "like_users" : {
        "u9bxggdTQUgZvNJXmdMsQAeGD2z2" : true,
        "u9bxggdTQUgZRGERgrEgregerGER" : true
      },
      "name" : "Event - test",
      "uid" : "u9bxggdTQUgZvNJXmdMsQAeGD2z2"
    }
  },
```

we need to build a new Where end for setting the consultations within the collection array.

any ideas?

**Comment by davideast** [comment]
Your structure is too nested for Querybase to use. Querybase works off the Firebase Database best practice of keep your data shallow. Rather than query using an object of `user_list`, you should create a root data structure of `user_list` and query from there.
