### ISSUE TITLE
React Native Setup Issues

### ISSUE THREAD

**Issue by quadsurf** [davideast/Querybase#27]
Here's my set up, but it's not working...

import querybase from 'querybase';

let ref = firebase.database().ref();
let interestsRef = ref.child('interests/');
    let querybaseRef = querybase.ref(interestsRef,['active','photoUri']);
    let queriedDbRef = querybaseRef
      .where({
        active: true
      });
    queriedDbRef
      .on('value',
        (snap) => {
          console.log(snap.val());
        });

i get a red screen that says "null is not an object (evaluating 'firebase.auth().currentUser')"
but when i comment out the querybase code above, my firebase auth works perfectly, so some how these two modules auth and querybase are conflicting

any suggestions/ideas/advice? pls help

on a side note, my 'interests' node on firebase has a lot more properties than just 'active' and 'photoUri' , so i was also trying to use querybase as a way to limit the data i'm requesting down to just those two property keys... if querybase was not meant to limit my queries by specified property keys, how would i do that?

**Comment by jsayol** [comment]
Not much to go on but this might help: https://groups.google.com/d/msg/firebase-talk/836OyVNd_Yg/z4k1GHw7GAAJ

**Comment by davideast** [comment]
RN setup is outside the scope of this library. Closing due to Jsayol's helpful tip.
