### ISSUE TITLE
React Native with QueryBase:  _querybase2.default.ref__ is not a function

### ISSUE THREAD

**Issue by yogieputra8** [davideast/Querybase#31]
So I tried using Querybase with React Native and this is my code snippet:

```
    import querybase from 'querybase';
    import * as firebase from 'firebase';

    let ref__ = firebase.database().ref();
    let interestsRef = ref__.child('house_id/' + key_houseID + '/devices');
    let querybaseRef = querybase.ref__(interestsRef,['name','room_id']);
    let queriedDbRef = querybaseRef.where({room_id: 'yqcou0M5'});

    queriedDbRef.on('value', (snap) => {
      console.log(snap.val());
    });
```

<br/>
When I run the code I got the error:
[![Screen Shot 2016-10-14 at 12.03.40 AM.png](https://s18.postimg.org/yiaxl9xwp/Screen_Shot_2016_10_14_at_12_03_40_AM.png)](https://postimg.org/image/i7atoylet/)
<br/>
Can you guys help me how to solve this issue?

**Comment by davideast** [comment]
I've updated the library to use a UMD bundle, which should resolve these import issues.

**Comment by gielcobben** [comment]
I still have this issue..

**Comment by m00gl3** [comment]
I am also facing this issue (December 27th)
