### ISSUE TITLE
Querybase "query" method undefined.

### ISSUE THREAD

**Issue by linuxs** [davideast/Querybase#50]
# Undefined method "query"
I am getting undefined with the query method however the ref method works as intended. I've tried replacing my copy of the library with this repo a few times but I am still getting the same result.

Example:
`querybase.query(FIREBASEREF); //undefined`
`querybase.ref(FIREBASEREF, []);`

**Comment by davideast** [comment]
Hi @linuxs!

There is no `query` method, just the `ref` method like you displayed above. What are you trying to achieve?

**Comment by linuxs** [comment]
Okay. Am I misunderstanding the example provided in the read me?

<img width="554" alt="screenshot 2017-01-12 18 09 54" src="https://cloud.githubusercontent.com/assets/4185092/21912194/69413896-d8f2-11e6-93f9-f2fed45750bc.png">

**Comment by davideast** [comment]
@linuxs Ah! Thank you for pointing that out. That shouldn't be `.query()` it should be `.ref()`

**Comment by linuxs** [comment]
Fantastic, thank you. I thought I was crazy for the longest time.  👍 💯 

I noticed if I did:

`querybase.Query` it existed but not just `query`

**Comment by davideast** [comment]
No need to go crazy, the mistake was mine :)

The docs are updated, thanks for catching this!
