### ISSUE TITLE
How to use OR statement and contains statement

### ISSUE THREAD

**Issue by TonGarcia** [davideast/Querybase#51]
Hi, Does Querybase have any kind of OR / Contains statements?  Is it possible to use something like where([item1, item2])?

**Comment by Domiii** [comment]
Querybase uses a very simple method that adds artificial composite indices, that are based on firebase queries which only allow *exact matching*. `Or` and `Contains` queries both require partial matching to be supported on the database side, but lack thereof is sadly a shortcoming by firebase (They have been promising more powerful query support for years, but...).

While we cannot add general `Or` or `Contains` queries, we could try find some work-arounds for some (rather limited) special cases.
