### ISSUE TITLE
How to import and use Querybase in Angular2 project?

### ISSUE THREAD

**Issue by pedrohills** [davideast/Querybase#55]
Every time that i run npm install command, the querybase library is coming with less files that expected.

**Comment by pedrohills** [comment]
I'm having the same problem here, after clone repository I get fewer files, not all.

**Comment by flavionc** [comment]
I'm having the same problem here, after clone repository I get fewer files, not all.

**Comment by vvthinh** [comment]
Unhandled rejection TypeError: Cannot read property 'ref' of undefined

**Comment by davideast** [comment]
@pedrohills @flavionc @vvthinh Can you provide some example code?

**Comment by dmitriismirnov** [comment]
can I add this library in Android Studio using something like compile 'davideast.querybase.etc'?

**Comment by ajmakhl** [comment]
using react native

```
import firebase from 'firebase';
import querybase from 'querybase';
```

```
const rr = firebase.database().ref();
    const querybaseRef = querybase.ref(rr.child('fresh'), []);
    console.log(querybaseRef)
```

<img width="371" alt="screen shot 2017-05-15 at 4 47 29 pm" src="https://cloud.githubusercontent.com/assets/17507288/26078671/399fb02a-398e-11e7-8504-5991e9317944.png">

**Comment by eliocruz** [comment]
Up...
