### ISSUE TITLE
indexKey for correct UTF lexicographical ordering

### ISSUE THREAD

**Issue by Domiii** [davideast/Querybase#56]
The key separator in  [QuerybaseUtils.indexKey](https://github.com/davideast/Querybase/blob/master/src/QuerybaseUtils.ts#L35) is hardcoded as `'~~'` but should be `'\uffff'` to ensure correct lexicographical ordering with non-ASCII characters.

Currently, when using `'~~'` as separator, *shorter* ASCII keys are *later* in the lexicographical ordering:

```js
var a = ['aaa~~b~~', 'aa~~b~~', 'a~~b~~'];
a.sort()
```

`["aaa~~b~~", "aa~~b~~", "a~~b~~"]`

However, that ordering breaks down with non-ASCII characters because they come after tilde. Here is an example with the Chinese character for "love" (愛) and "you" (你):

```js
var a = ['愛~~b~~', '愛a~~b~~', '愛你~~b~~'];
a.sort()
```

`["愛a~~b~~", "愛~~b~~", "愛你~~b~~"]`

I'd recommend simply using `'\uffff'` (or two or three of those) instead, since it lexicographically is the last character in 16-bit Unicode encoding:

```js
var a = ['愛\uffffb\uffff', '愛a\uffffb', '愛你\uffffb\uffff'];
a.sort()
```

`["愛a￿b", "愛你￿b￿", "愛￿b￿"]`

You might want to suffix the last key with the separator for the same reason:

`'a\uffffb\uffff'` instead of `'a\uffffb'`

**Comment by davideast** [comment]
@Domiii Thank you so much for taking the time for creating a detailed issue! Are you also open to creating a PR?

**Comment by Domiii** [comment]
It would be a simple fix. Problem is: The change will not be backward compatible, in that anyone who already used Querybase will already have the wrong character in their DB, requiring active migration.

Everyone has their own opinion on migrations, so there is a lot of room for debate. AFAIK, Querybase does not even store it's own version in the DB? Arguably, the first thing you might want to do is add that. Then on initialization check version (if no version info found, then you know it's this, old, version). During initialization, if version is outdated, run corresponding set of migration scripts, step by step to update to latest version.

But that move not only makes querybase a lot less lighter, but also will start becoming a pain in the butt real fast. Case and point: Simply because there is no way of telling where in the DB, querybase has been used, we might have to offer global or selective migration. Global migration, for non-sensitive databases that are not super super huge already, basically looks for all possibly pre-existing keys in the entire DB, while selective migration lets the user choose a subset of paths that they know need fixing (and let's hope they don't forget any).

The alternative is: Pull an Angular, and don't offer a migration path?

Since no one has that much extra time, option 2 seems to be the better one, with the additional "leave it as is until too many people start complaining" decorator?

What do you think?
