### ISSUE TITLE
Confusing documentation: querybase.ref without index

### ISSUE THREAD

**Issue by Domiii** [davideast/Querybase#57]
`querybase.ref` expects two arguments. If you try to wrap a `ref` without the index argument, you get an error:

> No indexes provided in the Querybase constructor. Querybase uses the indexOn() getter to create the composite queries for the where() method.

However [the README](https://github.com/davideast/Querybase#querying-using-one-field) proposes that this is a valid line:

```js
const querybaseRef = querybase.ref(databaseRef);
```

And somehow allows querying any single field, individually? Has this been deprecated, or...?

**Comment by davideast** [comment]
Thanks for flagging this!
