### ISSUE TITLE
Can I use Querybase with angular 2 or 4. is that posible??

### ISSUE THREAD

**Issue by atlabiz** [davideast/Querybase#59]
I want to query some data that I have in Firebase. but I don't know why is not work for me. i is return an empty array. 

+ when I try to install the Querybase i have this errors

```cmd
ndows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop> npm install querybase --save
npm ERR! path C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop\node_modules\@types\node
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop\node_modules\@types\node'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop\node_modules\@types\no
de'
npm ERR!     at Error (native)
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop\node_modules\@types\
node'
npm ERR!        at Error (native)
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Users\\Developer\\Documents\\GitHub\\DRUG-EN-DDROP-STAGING\\Test-drugendrop\\node_modules\\@types\\node' },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\Developer\\Documents\\GitHub\\DRUG-EN-DDROP-STAGING\\Test-drugendrop\\node_modules\\@types\\node',
npm ERR!   parent: 'project1' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.0.1 → 5.0.3    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Developer\AppData\Roaming\npm-cache\_logs\2017-06-15T10_00_00_877Z-debug.log
PS C:\Users\Developer\Documents\GitHub\DRUG-EN-DDROP-STAGING\Test-drugendrop> npm install querybase --save
```

**Comment by jbeckton** [comment]
Do yourself a favor and switch to the Parse Platform. I have been looking at Firebase really hard for a week or so because I thought I wanted to use it for a project or two but once I saw how lackluster the API is around querying and filtering I've seen enough to deter me from it. Looks like you have to add properties and such as well as structure your data based on Firebase inability to allow you to perform simple quires on multiple properties. It baffles me as to why this particular library could not be part of the SDK and supported by Google.

**Comment by George35mk** [comment]
@davideast  Can you update the library for new firebase version I use angular 4 and have errors when I import your library, I build a very big project for a company and I want to query multiple queries and I can't to that, only your lib can save me but needs an update.

**Comment by hananurrehman** [comment]
Honestly this really annoying, firebase is such a great platform for authentication and realtime database but nobody on the dev team seems to care about adding something as simple as "where' clause
I wanted to fetch random data from firebase and i have been banging my head in the wall for a month without a proper solution now

**Comment by George35mk** [comment]
Bro look when i ask this question 2 jul 2017

Now is 10 Sept 2017, What are you think ?? I found solution or no?
:) :) :)

**Comment by George35mk** [comment]
I am 2 bilion years away trust me

**Comment by davideast** [comment]
@jbeckton @hananurrehman @George35mk This library is now longer needed now that we have [Cloud Firestore](https://firebase.google.com/docs/firestore/).
